apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: {{ .Values.InferenceService.name }}
spec:
  predictor:
    # to disable scaling to zero
    minReplicas: 1
    serviceAccountName: {{ .Values.InferenceService.serviceAccountName }} 
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: {{ .Values.InferenceService.storageUri }}
      resources:
        requests:
          cpu: "200m"  # Adjusted CPU request
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
