alertmanager:
  ## Deploy alertmanager
  ##
  enabled: false
grafana:
  # username is 'admin'
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      #kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts: ['grafana.kubernetes.local']
    path: "/"
    tls:
    - secretName: tls-credential
      hosts:
      - grafana.kubernetes.local
    spec:
      ingressClassName: nginx
      #service:
    #type: NodePort
prometheus:
  ingress:
    enabled: true
    #annotations:
      #      kubernetes.io/ingress.class: nginx
    hosts: ['prometheus.kubernetes.local']
    paths: ['/'] # does not need regex capture like others
    tls:
    - secretName: tls-credential
      hosts:
      - prometheus.kubernetes.local
    spec:
      ingressClassName: nginx
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    externalUrl: "https://prometheus.kubernetes.local/prometheus"
    routePrefix: /
# TODO - finish Thanos configuration
# thanos:
## Thanos configuration allows configuring various aspects of a Prometheus server in a Thanos environment.
## This section is experimental, it may change significantly without deprecation notice in any release.
## This is experimental and may change significantly without backward compatibility in any release.
## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosspec
